apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workloadplacementpolicies.guardian.io
spec:
  group: guardian.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workloadSelector:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                criteria:
                  type: object
                  properties:
                    cost:
                      type: object
                      properties:
                        weight: {type: integer}
                        threshold: {type: number}
                    latency:
                      type: object
                      properties:
                        weight: {type: integer}
                        maxAcceptable: {type: integer}
                    compliance:
                      type: object
                      properties:
                        weight: {type: integer}
                        rules:
                          type: array
                          items:
                            type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: workloadplacementpolicies
    singular: workloadplacementpolicy
    kind: WorkloadPlacementPolicy
    shortNames:
    - wpp
