apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guardian-role
rules:
  - apiGroups: ["guardian.io"]
    resources: ["workloadplacementpolicies", "cloudenvironments"]
    verbs: ["list", "watch", "patch", "get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guardian-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guardian-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
